### PR TITLE
fixed spelling error

### PR DESCRIPTION
**Pull request by b0yfriend**
ur welc

### CODE REVIEW

**Comment by b0yfriend** [comment]
wow it looks illegible in the diff view -- it's the doot doot skeleton playing trumpet haha

**Comment by IanMitchell** [comment]
Alas, it doesn't look like it works on the profile screen either

**Comment by IanMitchell** [comment]
we tried

**Comment by b0yfriend** [comment]
LOL i did not expect you to merge, but thank you

here is your reward

Screen Shot 2020-07-10 at 7 02 53 PM

**Pull request merged**
